name: wallpaper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: any
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+9
  cached_network_image: ^2.0.0
  random_string: ^2.0.1
  camera: ^0.5.8+11
  shared_preferences: ^0.5.12+2
  image_picker: ^0.6.7+1
  image_cropper: ^1.2.2
  firebase_storage: ^3.1.6
  scoped_model: ^1.0.1
  moor_flutter: ^2.0.0
  simple_animations: ^1.3.4
  flutter_local_notifications: ^0.8.4+3
  fluttertoast: ^3.1.3
  draggable_scrollbar: ^0.0.4
  firebase_database: ^3.1.1
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.3
  search_widget: ^1.0.2
  flutter_spinkit: ^4.1.2
  font_awesome_flutter: ^8.2.0
  google_fonts: ^1.1.0
  url_launcher: ^5.4.2
  substring_highlight: ^0.1.2
  flutter_responsive_screen:
  firebase_analytics: ^5.0.11
  collection_ext: ^0.2.0
  provider: ^4.0.2
  tuple: ^1.0.3
  intl: ^0.16.1
  flutter_screenutil: ^1.0.2
  folding_cell: ^1.0.0
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  sqflite: ^1.3.0
  path: ^1.6.4
  date_format: ^1.0.8
  flutter_swiper: ^1.1.6
  cupertino_icons: ^0.1.3
  flutter_tts:
  date_range_picker: ^1.0.3
  auto_size_text: ^2.0.2
  page_transition: ^1.1.4
  flutter_chess_board: ^0.9.4
  chess_vectors_flutter: ^1.0.6
  flutter_statusbar_manager: ^1.0.2
dev_dependencies:
  bloc_test: ^4.0.0
  effective_dart: ^1.2.0
  flutter_launcher_name: "^0.0.1"
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
flutter_launcher_name:
  name: "Medic"
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/login/
     - assets/icon/dashboard/
     - assets/icon/games/
     - assets/icon/memory/
     - assets/icon/Quiz/
     - assets/Json/
     - res/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 500
    - family: Blackcherry
      fonts:
        - asset: fonts/blackcherry.ttf
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
